# Autogenerated by devscripts/update-version.py

__version__ = '2025.05.28.232948'

RELEASE_GIT_HEAD = '201812100f315c6727a4418698d5b4e8a79863d4'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.05.28.232948'
